# Generated by Django 3.2.16 on 2023-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_patient_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status_update',
            field=models.CharField(choices=[('RHU', 'RHU'), ('Referred to MCH', 'Referred to MCH')], default='RHU', max_length=50),
        ),
    ]
