# Generated by Django 3.2.16 on 2023-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_patient_status_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='supply_unit',
        ),
        migrations.AlterField(
            model_name='drug',
            name='supply_unit',
            field=models.IntegerField(default=0),
        ),
    ]
